export const UI_TIMINGS = {
  TOAST_DURATION_MS: 4000,
  AUTO_FOCUS_DELAY_MS: 50,
} as const;

export const VALIDATION_RULES = {
  MIN_PASSWORD_LENGTH: 6,
  MIN_NAME_LENGTH: 2,
  MAX_NAME_LENGTH: 100,
  MIN_TITLE_LENGTH: 3,
  MAX_TITLE_LENGTH: 255,
  MIN_DESCRIPTION_LENGTH: 10,
  MIN_LOCATION_LENGTH: 2,
  MAX_LOCATION_LENGTH: 255,
  MIN_TAG_LENGTH: 2,
  MAX_TAG_LENGTH: 50,
} as const;

export const REGEX_PATTERNS = {
  HEX_COLOR: /^#([0-9A-Fa-f]{6}|[0-9A-Fa-f]{3})$/,
} as const;
