export const ERROR_CODES = {
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_2FA_CODE: 'INVALID_2FA_CODE',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  PRIVATE_EVENT_FORBIDDEN: 'PRIVATE_EVENT_FORBIDDEN',
  FORBIDDEN: 'FORBIDDEN',
  CAPACITY_REACHED: 'CAPACITY_REACHED',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
